/turf/open
	/// Higher-priority open turfs draw their edge over lower-priority turfs.
	/// 0 means this turf participates without overriding lower-priority tiles.
	var/edge_priority = 0

	/// If TRUE, this turf only provides N/S/E/W edge sprites.
	var/cardinal_edges_only = FALSE

	/// Edge overlays currently generated for this turf.
	var/list/image/edge_overlays


/turf/open/Initialize(mapload)
	// Mapload builds every neighbor before anyone should look at edges.
	// A per-turf refresh here redraws the same corner once per adjacent tile.
	if(!mapload)
		update_edges()
		refresh_blend_neighbors()

	. = ..()

/turf/open/Destroy()
	clear_edge_overlays()
	return ..()


/// Drops edge corners that were painted by a turf which has since been replaced.
/turf/proc/refresh_neighbor_edges()
	for(var/turf/open/neighbor in RANGE_TURFS(1, src))
		if(neighbor == src || !neighbor.edge_overlays)
			continue
		// Still inside the reservation: its own Destroy drops the overlay.
		if(neighbor.turf_flags & RESERVATION_TURF)
			continue
		neighbor.update_edges()


/// Returns this turf's edge blending priority.
/turf/open/proc/get_blend_priority()
	return edge_priority


/// Returns whether this turf only provides cardinal edge sprites.
/turf/open/proc/uses_cardinal_edges_only()
	return cardinal_edges_only


/// Returns TRUE if this turf has a valid icon that can provide the requested edge state.
/turf/open/proc/has_edge_state(direction)
	if(!icon || !direction)
		return FALSE

	if(cardinal_edges_only && (direction & (direction - 1)))
		return FALSE

	var/edge_state = TURF_EDGE_STATE_FOR_DIR(direction)
	if(!edge_state)
		return FALSE

	return icon_exists(icon, edge_state)


/// Returns TRUE if this turf can actually contribute an edge overlay.
/turf/open/proc/can_provide_edge(direction)
	if(!icon || isnull(edge_priority))
		return FALSE

	if(cardinal_edges_only && (direction & (direction - 1)))
		return FALSE

	return has_edge_state(direction)


/// Clears edge overlays generated by the generic blending system.
/turf/open/proc/clear_edge_overlays()
	if(!edge_overlays)
		return

	cut_overlay(edge_overlays)
	edge_overlays = null


/// Stores newly generated edge overlays.
/turf/open/proc/store_edge_overlays(list/new_overlays)
	if(!new_overlays || !length(new_overlays))
		edge_overlays = null
		return

	edge_overlays = new_overlays


/// Rebuilds all edge overlays for this turf.
/turf/open/proc/update_edges(turf/from)
	rebuild_edges(from)


/// Refreshes nearby open turfs after this turf changes.
/turf/open/proc/refresh_blend_neighbors()
	for(var/turf/open/neighbor in RANGE_TURFS(1, src))
		if(neighbor == src)
			continue
		if(isnull(neighbor.get_blend_priority()))
			continue
		neighbor.update_edges(src)


/// Rebuilds the overlays contributed by higher-priority neighboring turfs.
/turf/open/proc/rebuild_edges(turf/from)
	if(!icon)
		clear_edge_overlays()
		return

	var/src_priority = get_blend_priority()
	if(isnull(src_priority))
		clear_edge_overlays()
		return

	clear_edge_overlays()

	var/list/new_overlays = list()

	for(var/direction in GLOB.alldirs)
		if(!direction)
			continue

		var/turf/open/neighbor = turf_wrap_step(src, direction)
		if(!neighbor || neighbor == src || !istype(neighbor, /turf/open))
			continue

		var/neighbor_priority = neighbor.get_blend_priority()
		if(isnull(neighbor_priority) || neighbor_priority <= src_priority)
			continue
		if(istype(src, /turf/open/rimworld/grass) && istype(neighbor, /turf/open/rimworld/grass))
			continue

		var/bleed_dir = REVERSE_DIR(direction)

		if(neighbor.uses_cardinal_edges_only() && (bleed_dir & (bleed_dir - 1)))
			continue

		if(!neighbor.can_provide_edge(bleed_dir))
			continue

		var/edge_state = TURF_EDGE_STATE_FOR_DIR(bleed_dir)
		if(!edge_state || !icon_exists(neighbor.icon, edge_state))
			continue

		var/mutable_appearance/edge = mutable_appearance(
			neighbor.icon,
			edge_state,
			layer + 0.01 + (neighbor_priority * 0.0001),
			appearance_flags = RESET_COLOR | RESET_ALPHA | RESET_TRANSFORM | KEEP_APART
		)

		edge.color = neighbor.color
		new_overlays += edge

	if(length(new_overlays))
		add_overlay(new_overlays)
		store_edge_overlays(new_overlays)
