// Which screen objects move as one when the chat browser is sitting over them.

/datum/hud/human/get_displacement_groups()
	return list(
		// Right-side status column
		list(HUD_MOB_HEALTH, HUD_MOB_HEALTHDOLL, HUD_MOB_STAMINA, HUD_MOB_SPACESUIT,
			HUD_MOB_MOOD, HUD_MOB_HUNGER, HUD_MOB_BLOOD_LEVEL, HUD_MOB_STYLE_METER),
		// Bottom-right controls
		list(HUD_MOB_INTENTS, HUD_MOB_MOVE_INTENT, HUD_MOB_ZONE_SELECTOR,
			HUD_MOB_THROW, HUD_MOB_CRAFTING_MENU, HUD_MOB_NAVIGATE_MENU,
			HUD_MOB_MEMORIES, HUD_MOB_PULL, HUD_MOB_AREA_CREATOR, HUD_MOB_COMBO,
			HUD_MOB_REST, HUD_MOB_SLEEP, HUD_MOB_RESIST,
			HUD_MOB_FLOOR_CHANGER, HUD_MOB_LANGUAGE_MENU),
		// Clothing grid
		list(HUD_KEY_ITEM_SLOT(ITEM_SLOT_OCLOTHING), HUD_KEY_ITEM_SLOT(ITEM_SLOT_ICLOTHING),
			HUD_KEY_ITEM_SLOT(ITEM_SLOT_GLOVES), HUD_KEY_ITEM_SLOT(ITEM_SLOT_EYES),
			HUD_KEY_ITEM_SLOT(ITEM_SLOT_EARS), HUD_KEY_ITEM_SLOT(ITEM_SLOT_MASK),
			HUD_KEY_ITEM_SLOT(ITEM_SLOT_HEAD), HUD_KEY_ITEM_SLOT(ITEM_SLOT_FEET),
			HUD_KEY_ITEM_SLOT(ITEM_SLOT_NECK), HUD_HUMAN_TOGGLE_INVENTORY),
		// Item bar
		list(HUD_KEY_ITEM_SLOT(ITEM_SLOT_ID), HUD_KEY_ITEM_SLOT(ITEM_SLOT_BELT),
			HUD_KEY_ITEM_SLOT(ITEM_SLOT_BACK), HUD_KEY_ITEM_SLOT(ITEM_SLOT_SUITSTORE),
			HUD_KEY_ITEM_SLOT(ITEM_SLOT_LPOCKET), HUD_KEY_ITEM_SLOT(ITEM_SLOT_RPOCKET),
			HUD_KEY_HAND_SLOT(1), HUD_KEY_HAND_SLOT(2),
			HUD_MOB_SWAPHAND_1, HUD_MOB_SWAPHAND_2, HUD_MOB_DROP),
	)

/datum/hud/living/get_displacement_groups()
	return list(
		list(HUD_MOB_HEALTHDOLL, HUD_MOB_STAMINA),
		list(HUD_MOB_PULL, HUD_MOB_INTENTS, HUD_MOB_FLOOR_CHANGER,
			HUD_MOB_LANGUAGE_MENU, HUD_MOB_MEMORIES),
	)

/datum/hud/dextrous/get_displacement_groups()
	return list(
		list(HUD_MOB_HEALTHDOLL),
		list(HUD_MOB_DROP, HUD_MOB_SWAPHAND_2, HUD_MOB_PULL,
			HUD_MOB_INTENTS, HUD_MOB_FLOOR_CHANGER, HUD_MOB_ZONE_SELECTOR,
			HUD_MOB_AREA_CREATOR, HUD_MOB_MEMORIES, HUD_MOB_THROW,
			HUD_KEY_HAND_SLOT(1), HUD_KEY_HAND_SLOT(2)),
	)

/datum/hud/dextrous/voidwalker/get_displacement_groups()
	. = ..()
	. += list(list(HUD_VOIDWALKER_SPACE_CAMO, HUD_VOIDWALKER_VOID_JUMP))

/datum/hud/robot/get_displacement_groups()
	return list(
		list(HUD_MOB_HEALTH),
		list(HUD_CYBORG_HANDS, HUD_CYBORG_LAMP, HUD_SILICON_ALERTS,
			HUD_MOB_INTENTS, HUD_MOB_ZONE_SELECTOR, HUD_MOB_PULL,
			HUD_KEY_HAND_SLOT(1), HUD_KEY_HAND_SLOT(2), HUD_KEY_HAND_SLOT(3),
			HUD_MOB_FLOOR_CHANGER, HUD_MOB_LANGUAGE_MENU, HUD_MOB_NAVIGATE_MENU, HUD_MOB_MEMORIES),
		list(HUD_SILICON_TAKE_IMAGE, HUD_CYBORG_RADIO, HUD_SILICON_TABLET),
	)

/datum/hud/ai/get_displacement_groups()
	return list(
		list(HUD_AI_SENSORS, HUD_AI_CAMERA_LIGHT, HUD_AI_CAMERA_TRACK,
			HUD_AI_CAMERA_LIST, HUD_AI_IMAGE_VIEW, HUD_AI_CREW_MONITOR,
			HUD_AI_CREW_MANIFEST, HUD_SILICON_ALERTS, HUD_AI_AICORE,
			HUD_AI_CALL_SHUTTLE, HUD_AI_ANNOUNCEMENT, HUD_AI_STATE_LAWS,
			HUD_SILICON_TABLET, HUD_AI_MULTICAM, HUD_AI_ADD_MULTICAM,
			HUD_AI_TAKE_IMAGE, HUD_MOB_LANGUAGE_MENU, HUD_MOB_MEMORIES),
		list(HUD_AI_FLOOR_INDICATOR, HUD_AI_GO_UP, HUD_AI_GO_DOWN),
	)

/datum/hud/pai/get_displacement_groups()
	return list(
		list(HUD_PAI_SOFTWARE, HUD_PAI_SHELL, HUD_PAI_CHASSIS,
			HUD_AI_STATE_LAWS, HUD_CYBORG_LAMP, HUD_MOB_REST),
		list(HUD_PAI_HOST_MONITOR, HUD_PAI_GPS, HUD_PAI_NEWSCASTER,
			HUD_AI_CREW_MANIFEST, HUD_SILICON_TABLET),
		list(HUD_AI_TAKE_IMAGE, HUD_AI_IMAGE_VIEW, HUD_CYBORG_RADIO),
		list(HUD_MOB_HEALTHDOLL, HUD_MOB_LANGUAGE_MENU, HUD_MOB_NAVIGATE_MENU, HUD_MOB_MEMORIES),
	)

/datum/hud/alien/get_displacement_groups()
	return list(
		list(HUD_MOB_HEALTH, HUD_ALIEN_PLASMA_DISPLAY, HUD_ALIEN_QUEEN_FINDER),
		list(HUD_MOB_INTENTS, HUD_MOB_ZONE_SELECTOR, HUD_MOB_DROP,
			HUD_MOB_THROW, HUD_MOB_PULL, HUD_MOB_REST, HUD_MOB_SLEEP, HUD_MOB_RESIST,
			HUD_MOB_NAVIGATE_MENU, HUD_MOB_MEMORIES, HUD_ALIEN_HUNTER_LEAP,
			HUD_MOB_FLOOR_CHANGER, HUD_MOB_LANGUAGE_MENU,
			HUD_KEY_HAND_SLOT(1), HUD_KEY_HAND_SLOT(2),
			HUD_MOB_SWAPHAND_1, HUD_MOB_SWAPHAND_2),
	)

/datum/hud/larva/get_displacement_groups()
	return list(
		list(HUD_MOB_HEALTH, HUD_ALIEN_QUEEN_FINDER),
		list(HUD_MOB_INTENTS, HUD_MOB_ZONE_SELECTOR, HUD_MOB_PULL,
			HUD_MOB_REST, HUD_MOB_SLEEP, HUD_MOB_NAVIGATE_MENU, HUD_MOB_MEMORIES,
			HUD_MOB_FLOOR_CHANGER, HUD_MOB_LANGUAGE_MENU),
	)

/datum/hud/blob_overmind/get_displacement_groups()
	return list(
		list(HUD_MOB_HEALTH, HUD_BLOB_POWER_DISPLAY),
		list(HUD_BLOB_BLOBBERNAUT, HUD_BLOB_RESOURCES, HUD_BLOB_NODE,
			HUD_BLOB_FACTORY, HUD_BLOB_READAPT, HUD_BLOB_RELOCATE,
			HUD_BLOB_JUMP_TO_CORE, HUD_BLOB_JUMP_TO_NODE),
	)

/datum/hud/guardian/get_displacement_groups()
	return list(
		list(HUD_MOB_HEALTH),
		list(HUD_GUARDIAN_COMMUNICATE, HUD_GUARDIAN_MANIFEST,
			HUD_GUARDIAN_RECALL, HUD_GUARDIAN_TOGGLE, HUD_GUARDIAN_LIGHT,
			HUD_MOB_PULL, HUD_MOB_INTENTS, HUD_MOB_FLOOR_CHANGER),
	)

/datum/hud/ghost/get_displacement_groups()
	var/list/hudboxes = list()
	for(var/index in 1 to 10) // covers every hudbox subtype with room to spare
		hudboxes += HUD_KEY_GHOST_HUDBOX(index)
	return list(
		list(HUD_GHOST_SPAWNERS, HUD_GHOST_ORBIT, HUD_GHOST_REENTER_CORPSE,
			HUD_GHOST_DNR, HUD_GHOST_TELEPORT, HUD_GHOST_SETTINGS,
			HUD_GHOST_MINIGAMES, HUD_MOB_LANGUAGE_MENU, HUD_MOB_FLOOR_CHANGER),
		hudboxes,
	)
