export const TOOLTIPS = {
  consciousness:
    'Current level of wakefulness and awareness. Severe hypoperfusion, hypoxia, shock, or pain can drive it toward unconsciousness.',
  pain: 'Total pain generated by active injuries. High pain contributes to shock, movement impairment, and loss of consciousness.',
  shock:
    'Systemic physiological stress caused by pain, hemorrhage, and poor circulation. Higher values impair consciousness and recovery.',
  heartbeat:
    'Current pulse and rhythm. The heart model derives bradycardia, tachycardia, ventricular tachycardia, and asystole from the actual cardiac state.',
  cardiacOutput:
    'Relative cardiac output. It depends on heart rate, myocardial contractility, and stroke efficiency.',
  bloodPressure:
    'Current systemic blood pressure derived from cardiac output and circulating blood volume.',
  perfusion:
    'Relative cerebral perfusion derived from blood pressure. Low perfusion reduces brain oxygen delivery.',
  bloodVolume:
    'Current circulating blood volume relative to the normal volume. Major blood loss lowers blood pressure and organ perfusion.',
  breathing:
    'Whether ventilation is currently effective. Failed or impaired breaths lower blood oxygenation.',
  oxygenation:
    'Blood oxygen saturation produced by the lungs. Low saturation reduces oxygen delivery to the brain and other tissues.',
  ventilation:
    'Effective lung ventilation after accounting for lung damage and fluid accumulation.',
  bleedRate:
    'Current blood loss per second from active injuries. Arterial bleeding is affected by the current cardiac pulse and blood pressure.',
  lungFluid:
    'Fluid accumulation in the lungs. Higher levels reduce effective ventilation and oxygen exchange.',

  cardiogram:
    'Live ECG-style trace generated from the current heart rhythm. A flatline represents asystole.',

  bodyDoll: 'Select a body part or organ to inspect its condition.',
  limbMissing: 'This limb is absent.',
  limbDisabled:
    'This limb cannot be used because of severe injury or disability.',
  limbBrute: 'Physical blunt trauma affecting this body part.',
  limbBurn: 'Thermal or chemical burn damage affecting this body part.',
  limbBleeding: 'Current blood loss rate originating from this body part.',

  organBrain:
    'Central nervous system. Brain oxygen and blood perfusion directly affect consciousness and survival.',
  brainOxygen:
    'Current oxygen reserve of the brain. Persistent severe hypoxia causes irreversible brain damage.',
  organHeart:
    'The heart determines pulse, cardiac output, and systemic blood pressure. Failure or asystole rapidly eliminates cerebral perfusion.',
  organLungs:
    'The lungs determine ventilation and blood oxygenation. Damage or fluid accumulation reduces oxygen delivery.',
  organFailing:
    'This organ is failing and is no longer performing at full capacity.',
  organMissing: 'This organ is absent.',

  injuryList: 'Active medical conditions affecting the selected body part.',
  injuryDisabling: 'This injury prevents normal use of the body part.',
  injuryBleed: 'Blood loss currently contributed by this injury.',

  close: 'Close the health panel.',
  selectHint:
    'Select a body part or organ in the center to inspect its detailed state.',
} as const;
