#ifndef OLD_COMBAT_SYSTEM
/obj/item/bodypart
	/// Sharp tissue density (mm RHA) — reduces AP after this layer takes damage.
	var/density_sharp = BODYPART_DENSITY_SHARP_DEFAULT
	/// Blunt tissue density (MPa).
	var/density_blunt = BODYPART_DENSITY_BLUNT_DEFAULT

	/// Natural armor on this part (carapace etc.), same units as clothing.
	var/natural_sharp_armor = 0
	var/natural_blunt_armor = 0

	var/list/injuries
	var/injury_damage_multiplier = 1.0
	var/current_pain = 0

/obj/item/bodypart/proc/update_injuries(replaced = FALSE)
	var/new_multiplier = 1.0
	var/new_pain = 0

	for(var/datum/injury/injury as anything in injuries)
		new_multiplier *= injury.get_damage_multiplier()
		new_pain += injury.get_pain()

	injury_damage_multiplier = min(new_multiplier, MAX_INJURY_DAMAGE_MULTIPLIER)
	current_pain = new_pain

	if(owner)
		owner.update_pain_from_limb(src)

	refresh_bleed_rate()

/**
 * Returns existing injury on this limb with the given series, or null.
 */
/obj/item/bodypart/proc/find_injury_series(series_id)
	for(var/datum/injury/injury as anything in injuries)
		if(injury.series == series_id)
			return injury
	return null

/obj/item/bodypart/proc/has_injury_type(injury_type)
	for(var/datum/injury/injury as anything in injuries)
		if(injury.type == injury_type)
			return TRUE
	return FALSE

/**
 * Returns the fraction of the limb's structural integrity that has been lost.
 *
 * Brute damage represents destruction of muscle, connective tissue,
 * bone and other physical structures.
 *
 * 0.0 = intact
 * 1.0 = completely destroyed
 */
/obj/item/bodypart/proc/get_physical_damage_ratio()
	if(max_damage <= 0)
		return 1
	return clamp(brute_dam / max_damage, 0, 1)

/**
 * Returns the fraction of the limb's skin integrity that has been lost.
 *
 * Burn damage represents destruction of the skin and superficial tissue.
 *
 * 0.0 = intact
 * 1.0 = completely destroyed
 */
/obj/item/bodypart/proc/get_skin_damage_ratio()
	if(max_damage <= 0)
		return 1
	return clamp(burn_dam / max_damage, 0, 1)

/obj/item/bodypart/proc/get_physical_integrity()
	return 1 - get_physical_damage_ratio()

/obj/item/bodypart/proc/get_skin_integrity()
	return 1 - get_skin_damage_ratio()

/**
 * Applies an injury generated from the resulting state of this bodypart.
 *
 * The injury datum handles upgrades, absorption and the physiological
 * response generated by applying the injury.
 */
/obj/item/bodypart/proc/apply_generated_injury(injury_type, attack_direction = null, damage_source = null, chance = 100)
	if(!injury_type)
		return null

	if(chance < 100 && !prob(chance))
		return null

	var/datum/injury/new_injury = new injury_type()
	return new_injury.apply_to_limb(src, attack_direction = attack_direction, source = damage_source)

/**
 * Generates injuries from the resulting condition of the bodypart.
 *
 * The current bodypart state determines severity, while the latest hit
 * determines how that state was produced.
 *
 * This allows injuries to accumulate over multiple hits instead of being
 * determined exclusively by the size of a single damage instance.
 */
/obj/item/bodypart/proc/try_generate_injuries(brute = 0, burn = 0, sharpness = NONE, attack_direction = null, damage_source, wound_bonus = 0, exposed_wound_bonus = 0)
	if(wound_bonus == CANT_WOUND)
		return

	if(!is_woundable())
		return

	var/physical_ratio = get_physical_damage_ratio()
	var/skin_ratio = get_skin_damage_ratio()
	var/physical_integrity = 1 - physical_ratio
	// var/skin_integrity = 1 - skin_ratio

	var/structural_hit = brute > 0
	var/thermal_hit = burn > 0

	/*
	 * ------------------------------------------------------------
	 * SKIN / SUPERFICIAL TISSUE
	 * ------------------------------------------------------------
	 */

	if(thermal_hit)
		if(skin_ratio >= 0.80)
			apply_generated_injury(/datum/injury/burn/critical, attack_direction, damage_source)
		else if(skin_ratio >= 0.45)
			apply_generated_injury(/datum/injury/burn/severe, attack_direction, damage_source)
		else if(skin_ratio >= 0.12)
			apply_generated_injury(/datum/injury/burn, attack_direction, damage_source)

		if(skin_ratio >= 0.35)
			apply_generated_injury(/datum/injury/skin_damage, attack_direction, damage_source, clamp((skin_ratio - 0.25) * 160, 20, 100))

	/*
	 * ------------------------------------------------------------
	 * SHARP TRAUMA
	 * ------------------------------------------------------------
	 */

	if(structural_hit && (sharpness & SHARP_EDGED))
		if(physical_ratio >= 0.70)
			apply_generated_injury(/datum/injury/laceration/critical, attack_direction, damage_source)
		else if(physical_ratio >= 0.35)
			apply_generated_injury(/datum/injury/laceration/severe, attack_direction, damage_source)
		else if(physical_ratio >= 0.08)
			apply_generated_injury(/datum/injury/laceration, attack_direction, damage_source)

	if(structural_hit && (sharpness & SHARP_POINTY))
		if(physical_ratio >= 0.65 && brute >= max_damage * 0.20)
			apply_generated_injury(/datum/injury/avulsion, attack_direction, damage_source)
		else
			apply_generated_injury(/datum/injury/puncture, attack_direction, damage_source, clamp(40 + physical_ratio * 100, 40, 100))

	/*
	 * ------------------------------------------------------------
	 * BLUNT STRUCTURAL DAMAGE
	 * ------------------------------------------------------------
	 */

	if(structural_hit && !(sharpness & (SHARP_EDGED | SHARP_POINTY)))
		if(physical_ratio >= 0.08)
			if(physical_ratio >= 0.40)
				apply_generated_injury(/datum/injury/contusion/severe, attack_direction, damage_source)
			else
				apply_generated_injury(/datum/injury/contusion, attack_direction, damage_source)

		if(physical_ratio >= 0.30)
			apply_generated_injury(/datum/injury/fracture, attack_direction, damage_source, clamp(45 + (physical_ratio - 0.30) * 120, 45, 100))

		if(physical_ratio >= 0.65)
			apply_generated_injury(/datum/injury/fracture/compound, attack_direction, damage_source, clamp((physical_ratio - 0.55) * 220, 30, 100))

	/*
	 * ------------------------------------------------------------
	 * SOFT-TISSUE DESTRUCTION
	 * ------------------------------------------------------------
	 */

	if(structural_hit && physical_ratio >= 0.50)
		apply_generated_injury(/datum/injury/nerve_damage, attack_direction, damage_source, clamp(35 + physical_ratio * 80, 35, 100))

	/*
	 * ------------------------------------------------------------
	 * LIMB-SPECIFIC JOINT FAILURE
	 * ------------------------------------------------------------
	 */

	if(structural_hit && (body_zone in list(BODY_ZONE_L_ARM, BODY_ZONE_R_ARM, BODY_ZONE_L_LEG, BODY_ZONE_R_LEG)) && physical_ratio >= 0.55)
		apply_generated_injury(/datum/injury/dislocation, attack_direction, damage_source, clamp((physical_ratio - 0.45) * 150, 20, 85))

	/*
	 * ------------------------------------------------------------
	 * HEAD TRAUMA
	 * ------------------------------------------------------------
	 */

	if(structural_hit && body_zone == BODY_ZONE_HEAD)
		if(physical_ratio >= 0.12)
			apply_generated_injury(/datum/injury/concussion, attack_direction, damage_source, clamp(45 + physical_ratio * 70, 45, 100))

		if(physical_ratio >= 0.32)
			apply_generated_injury(/datum/injury/skull_fracture, attack_direction, damage_source, clamp((physical_ratio - 0.25) * 180, 30, 100))

		if(physical_ratio >= 0.55)
			apply_generated_injury(/datum/injury/facial_trauma, attack_direction, damage_source, clamp((physical_ratio - 0.45) * 180, 25, 100))

		if(physical_ratio >= 0.35 && ((sharpness & (SHARP_EDGED | SHARP_POINTY)) || physical_ratio >= 0.65))
			apply_generated_injury(/datum/injury/eye_trauma, attack_direction, damage_source, clamp((physical_ratio - 0.30) * 160, 20, 80))

		if(physical_ratio >= 0.60)
			apply_generated_injury(/datum/injury/jaw_fracture, attack_direction, damage_source, clamp((physical_ratio - 0.50) * 140, 20, 70))

	/*
	 * ------------------------------------------------------------
	 * CHEST TRAUMA
	 * ------------------------------------------------------------
	 *
	 * The chest is treated as a collection of structures that can fail
	 * independently: ribs, lungs, pleura, vessels and the heart.
	 */

	if(structural_hit && body_zone == BODY_ZONE_CHEST)
		var/chest_severity = physical_ratio

		if(chest_severity >= 0.22)
			apply_generated_injury(/datum/injury/rib_fracture, attack_direction, damage_source, clamp(40 + chest_severity * 70, 40, 100))

		if(chest_severity >= 0.58)
			apply_generated_injury(/datum/injury/rib_fracture/flail, attack_direction, damage_source, clamp((chest_severity - 0.50) * 180, 25, 90))

		if(chest_severity >= 0.40)
			apply_generated_injury(/datum/injury/internal_bleeding, attack_direction, damage_source, clamp((chest_severity - 0.30) * 130, 20, 85))

		if(chest_severity >= 0.32 && (sharpness & SHARP_POINTY))
			apply_generated_injury(/datum/injury/pneumothorax, attack_direction, damage_source, clamp(60 + chest_severity * 50, 60, 100))
		else if(chest_severity >= 0.60)
			apply_generated_injury(/datum/injury/pneumothorax, attack_direction, damage_source, clamp((chest_severity - 0.50) * 140, 15, 70))

		if(chest_severity >= 0.52)
			apply_generated_injury(/datum/injury/hemothorax, attack_direction, damage_source, clamp((chest_severity - 0.45) * 150, 15, 70))

		if(chest_severity >= 0.68)
			apply_generated_injury(/datum/injury/cardiac_trauma, attack_direction, damage_source, clamp((chest_severity - 0.60) * 180, 15, 75))

		if(chest_severity >= 0.72)
			apply_generated_injury(/datum/injury/spleen_rupture, attack_direction, damage_source, clamp((chest_severity - 0.65) * 140, 10, 55))

	/*
	 * ------------------------------------------------------------
	 * VASCULAR DAMAGE
	 * ------------------------------------------------------------
	 */

	if(structural_hit)
		var/vascular_chance = 0

		if(sharpness & SHARP_EDGED)
			vascular_chance = 30 + physical_ratio * 70
		else if(sharpness & SHARP_POINTY)
			vascular_chance = 35 + physical_ratio * 65
		else if(physical_ratio >= 0.45)
			vascular_chance = (physical_ratio - 0.35) * 100

		if(vascular_chance > 0)
			if(physical_ratio >= 0.60 && (sharpness & (SHARP_EDGED | SHARP_POINTY)) && prob(vascular_chance * 0.45))
				apply_generated_injury(/datum/injury/arterial_bleed, attack_direction, damage_source)
			else if(prob(vascular_chance))
				apply_generated_injury(/datum/injury/venous_bleed, attack_direction, damage_source)

	/*
	 * ------------------------------------------------------------
	 * AVULSION / CATASTROPHIC TISSUE FAILURE
	 * ------------------------------------------------------------
	 */

	if(structural_hit && physical_ratio >= 0.78 && ((sharpness & (SHARP_EDGED | SHARP_POINTY)) || brute >= max_damage * 0.25))
		apply_generated_injury(/datum/injury/avulsion, attack_direction, damage_source, clamp((physical_ratio - 0.70) * 250, 25, 100))

	if(structural_hit && physical_integrity <= 0.10)
		apply_generated_injury(/datum/injury/avulsion, attack_direction, damage_source, 100)


/**
 * Called when a bodypart takes damage.
 *
 * Brute damage represents structural destruction.
 * Burn damage represents skin and superficial tissue destruction.
 *
 * The latest impact is kept separately from stored bodypart damage so that
 * a hit can still cause pain, shock and consciousness loss even when the
 * bodypart has no remaining damage capacity.
 *
 * Injury generation happens after damage is committed, allowing injuries
 * to emerge from accumulated bodypart damage instead of only the latest hit.
 */
/obj/item/bodypart/proc/receive_damage(brute = 0, burn = 0, blocked = 0, updating_health = TRUE, forced = FALSE, required_bodytype = null, wound_bonus = 0, exposed_wound_bonus = 0, sharpness = NONE, attack_direction = null, damage_source, wound_clothing = TRUE)
	SHOULD_CALL_PARENT(TRUE)

	var/hit_percent = forced ? 1 : (100 - blocked) / 100
	if((!brute && !burn) || hit_percent <= 0)
		return FALSE

	if(!forced)
		if(owner)
			if(HAS_TRAIT(owner, TRAIT_GODMODE))
				return FALSE

			if(SEND_SIGNAL(owner, COMSIG_CARBON_LIMB_DAMAGED, src, brute, burn) & COMPONENT_PREVENT_LIMB_DAMAGE)
				return FALSE

		if(required_bodytype && !(bodytype & required_bodytype))
			return FALSE

	var/dmg_multi = CONFIG_GET(number/damage_multiplier) * hit_percent

	brute = round(max(brute * dmg_multi * brute_modifier * injury_damage_multiplier, 0), DAMAGE_PRECISION)
	burn = round(max(burn * dmg_multi * burn_modifier * injury_damage_multiplier, 0), DAMAGE_PRECISION)

	if(!brute && !burn)
		return FALSE

	/*
	 * Keep the resolved incoming impact separate from the amount that can
	 * still be stored by the bodypart.
	 */
	var/impact_brute = brute
	var/impact_burn = burn

	if(owner)
		var/obj/item/stack/medical/wrap/current_gauze = LAZYACCESS(applied_items, LIMB_ITEM_GAUZE)
		if(istype(current_gauze, /obj/item/stack/medical/wrap/gauze))
			var/obj/item/stack/medical/wrap/gauze/our_gauze = current_gauze
			our_gauze.get_hit(src)

	/*
	 * Acute combat response is based on the actual impact, not the remaining
	 * damage capacity of the bodypart.
	 */
	if(owner)
		if(impact_brute > 0)
			owner.apply_combat_impact_response(impact_brute, body_zone, BRUTE, damage_source)

		if(impact_burn > 0)
			owner.apply_combat_impact_response(impact_burn, body_zone, BURN, damage_source)

	/*
	 * Determine how much new damage the bodypart can actually store.
	 */
	var/remaining_capacity = max(max_damage - get_damage(), 0)
	var/incoming_total = impact_brute + impact_burn

	var/applied_brute = impact_brute
	var/applied_burn = impact_burn

	if(incoming_total > remaining_capacity && incoming_total > 0)
		var/capacity_ratio = remaining_capacity / incoming_total
		applied_brute = round(impact_brute * capacity_ratio, DAMAGE_PRECISION)
		applied_burn = round(impact_burn * capacity_ratio, DAMAGE_PRECISION)

	if(applied_brute > 0)
		set_brute_dam(brute_dam + applied_brute)

	if(applied_burn > 0)
		set_burn_dam(burn_dam + applied_burn)

	/*
	 * The bodypart state has now changed, so injury generation must happen
	 * after damage is committed.
	 */
	update_wound_theory()

	try_generate_injuries(brute = impact_brute, burn = impact_burn, sharpness = sharpness, attack_direction = attack_direction, damage_source = damage_source, wound_bonus = wound_bonus, exposed_wound_bonus = exposed_wound_bonus)

	/*
	 * Recalculate pain, bleeding and future damage modifiers after the
	 * newly generated injuries have been applied.
	 */
	if(owner && impact_brute > 0)
		if(try_dismember_from_damage(impact_brute, impact_burn, sharpness))
			return TRUE
	update_injuries()

	if(owner)
		if(can_be_disabled)
			update_disabled()

		if(updating_health)
			owner.updatehealth()

	return update_bodypart_damage_state()



/**
 * Returns the combined structural failure score of injuries on this bodypart.
 *
 * This represents actual anatomical destruction rather than generic damage.
 */
/obj/item/bodypart/proc/get_dismemberment_injury_score()
	var/score = 0

	for(var/datum/injury/injury as anything in injuries)
		if(injury.dismemberment_weight <= 0)
			continue
		score += injury.dismemberment_weight

	return score


/obj/item/bodypart/proc/has_dismemberment_injury()
	for(var/datum/injury/injury as anything in injuries)
		if(injury.dismemberment_weight > 0)
			return TRUE
	return FALSE


/obj/item/bodypart/proc/try_dismember_from_damage(brute, burn, sharpness = NONE)
	if(!owner || (body_zone in list(BODY_ZONE_HEAD, BODY_ZONE_CHEST)))
		return FALSE

	if(HAS_TRAIT(owner, TRAIT_NODISMEMBER) || !sharpness)
		return FALSE

	if(brute <= 0)
		return FALSE

	var/physical_ratio = clamp(brute_dam / max_damage, 0, 1)
	var/injury_score = get_dismemberment_injury_score()

	if(physical_ratio < 0.70)
		return FALSE

	if(injury_score <= 0)
		return FALSE

	var/chance = (physical_ratio - 0.70) * 170
	chance += injury_score * 7
	chance += clamp(brute / max_damage * 100, 0, 25)

	if(sharpness & SHARP_EDGED)
		chance += 20
	else if(sharpness & SHARP_POINTY)
		chance += 10

	chance = clamp(chance, 0, 100)

	if(physical_ratio >= 0.92 && injury_score >= 3.0)
		chance = 100

	if(!prob(chance))
		return FALSE

	return dismember(BRUTE, FALSE)

///Remove target limb from its owner, with side effects.
/obj/item/bodypart/proc/dismember(dam_type = BRUTE, silent=TRUE, wounding_type)
	if(!owner || (bodypart_flags & BODYPART_UNREMOVABLE))
		return FALSE
	var/mob/living/carbon/limb_owner = owner
	if(HAS_TRAIT(limb_owner, TRAIT_GODMODE) || HAS_TRAIT(limb_owner, TRAIT_NODISMEMBER))
		return FALSE

	var/obj/item/bodypart/affecting = limb_owner.get_bodypart(BODY_ZONE_CHEST)
	affecting.receive_damage(clamp(brute_dam/2 * affecting.body_damage_coeff, 15, 50), clamp(burn_dam/2 * affecting.body_damage_coeff, 0, 50), wound_bonus=CANT_WOUND) //Damage the chest based on limb's existing damage
	if(!silent)
		limb_owner.visible_message(span_danger("<B>[limb_owner]'s [name] is violently dismembered!</B>"))
	INVOKE_ASYNC(limb_owner, TYPE_PROC_REF(/mob, emote), "scream")
	playsound(limb_owner, 'sound/effects/dismember.ogg', 80, TRUE)
	limb_owner.add_mood_event("dismembered_[body_zone]", /datum/mood_event/dismembered, src)
	limb_owner.add_mob_memory(/datum/memory/was_dismembered, lost_limb = src)

	if (wounding_type)
		LAZYSET(limb_owner.body_zone_dismembered_by, body_zone, wounding_type)

	drop_limb(dismembered = TRUE)
	limb_owner.update_equipment_speed_mods()

	if(QDELETED(src)) //Could have dropped into lava/explosion/chasm/whatever
		return TRUE
	if(dam_type == BURN)
		burn()
		return TRUE

	// Assume we had our limb sliced/punched off by this point
	if(can_bleed())
		limb_owner.bleed(rand(20, 40))
	return TRUE

/obj/item/bodypart/chest/dismember(dam_type = BRUTE, silent=TRUE, wounding_type)
	if(!owner)
		return FALSE
	var/mob/living/carbon/chest_owner = owner
	if(bodypart_flags & BODYPART_UNREMOVABLE)
		return FALSE
	if(HAS_TRAIT(chest_owner, TRAIT_NODISMEMBER))
		return FALSE

	. = list()
	if(wounding_type != WOUND_BURN && isturf(chest_owner.loc) && can_bleed())
		chest_owner.add_splatter_floor(chest_owner.loc)
	playsound(get_turf(chest_owner), 'sound/misc/splort.ogg', 80, TRUE)
	var/list/droppable_organs= list()
	for(var/obj/item/organ/droppable in contents)
		droppable_organs |= droppable
	var/obj/item/organ/organ = pick(droppable_organs)
	if(organ)
		if(!organ.drop_when_organ_spilling)
			return
		var/org_zone = check_zone(organ.zone)
		if(org_zone != BODY_ZONE_CHEST)
			return
		organ.Remove(chest_owner)
		if(chest_owner.loc)
			organ.forceMove(chest_owner.loc)
		. += organ

	if(cavity_item)
		cavity_item.forceMove(chest_owner.loc)
		. += cavity_item
		cavity_item = null

/obj/item/bodypart/proc/drop_limb(special, dismembered, move_to_floor = TRUE)
	if(!owner)
		return
	var/atom/drop_loc = owner.drop_location()

	SEND_SIGNAL(owner, COMSIG_CARBON_REMOVE_LIMB, src, special, dismembered)
	SEND_SIGNAL(src, COMSIG_BODYPART_REMOVED, owner, special, dismembered)
	bodypart_flags &= ~BODYPART_IMPLANTED //limb is out and about, it can't really be considered an implant
	add_mob_blood(owner)
	owner.remove_bodypart(src, special)

	for(var/datum/scar/scar as anything in scars)
		scar.victim = null
		LAZYREMOVE(owner.all_scars, scar)

	var/mob/living/carbon/phantom_owner = update_owner(null) // so we can still refer to the guy who lost their limb after said limb forgets 'em
	update_limb(dropping_limb = TRUE)

	for(var/datum/injury/injury as anything in injuries)
		injury.remove_from_limb()

	if(!phantom_owner.has_embedded_objects())
		phantom_owner.clear_alert(ALERT_EMBEDDED_OBJECT)
		phantom_owner.clear_mood_event("embedded")

	if(!special)
		if(phantom_owner.dna)
			for(var/datum/mutation/mutation as anything in phantom_owner.dna.mutations) //some mutations require having specific limbs to be kept.
				if(mutation.limb_req && (mutation.limb_req == body_zone))
					to_chat(phantom_owner, span_warning("You feel your [mutation] deactivating from the loss of your [body_zone]!"))
					phantom_owner.dna.remove_mutation(mutation, mutation.sources)

	update_icon_dropped()
	phantom_owner.update_health_hud() //update the healthdoll
	phantom_owner.update_body()
	if(!special)
		phantom_owner.hud_used?.update_locked_slots()

	if(bodypart_flags & (BODYPART_PSEUDOPART|BODYPART_STUMP))
		drop_organs(phantom_owner) //Psuedoparts shouldn't have organs, but just in case
		if(!QDELING(src)) // we might be removed as a part of something qdeling us
			qdel(src)
		return

	if(move_to_floor)
		if(!drop_loc) // drop_loc = null happens when a "dummy human" used for rendering icons on prefs screen gets its limbs replaced.
			qdel(src)
			return
		forceMove(drop_loc)

	SEND_SIGNAL(phantom_owner, COMSIG_CARBON_POST_REMOVE_LIMB, src, special, dismembered)

/obj/item/bodypart/proc/dismemberable_by_total_damage()
	return FALSE

/**
 * Applies an already-resolved penetration packet to this limb, then
 * processes body density and any internal organs.
 */
/obj/item/bodypart/proc/take_penetrating_hit(list/packet, sharpness = NONE, wound_bonus = 0, attack_direction, damage_source)
	if(!packet || !owner)
		return

	var/dealt = packet["limb_damage"]
	var/damage_type = packet["damage_type"]

	if(dealt > 0)
		var/brute = (damage_type == BRUTE) ? dealt : 0
		var/burn = (damage_type == BURN) ? dealt : 0

		receive_damage(brute = brute, burn = burn, blocked = 0, forced = TRUE, wound_bonus = wound_bonus, sharpness = sharpness, attack_direction = attack_direction, damage_source = damage_source)

	pen_apply_body_density(packet, density_sharp, density_blunt)

	if(pen_can_penetrate_deeper(packet))
		damage_organs_from_packet(packet)

/obj/item/bodypart/proc/damage_organs_from_packet(list/packet)
	var/list/candidates = list()

	for(var/obj/item/organ/O in src)
		if(O.organ_flags & ORGAN_EXTERNAL)
			continue
		candidates += O

	if(!length(candidates))
		return

	var/obj/item/organ/target = pick(candidates)
	var/organ_damage = packet["damage"] * 0.5

	if(organ_damage < 0.5)
		return

	pen_apply_body_density(packet, target.density_sharp, target.density_blunt)
	target.apply_organ_damage(organ_damage)
	target.on_external_damage(organ_damage, packet, null)
#endif
