#ifndef OLD_COMBAT_SYSTEM
/**
 * Applies an injury generated from the resulting state of this bodypart.
 *
 * The injury datum handles upgrades, absorption and the physiological
 * response generated by applying the injury.
 */
/obj/item/bodypart/proc/apply_generated_injury(injury_type, attack_direction = null, damage_source = null, chance = 100)
	if(!injury_type)
		return null

	if(chance < 100 && !prob(chance))
		return null

	var/datum/injury/new_injury = new injury_type()
	return new_injury.apply_to_limb(src, attack_direction = attack_direction, source = damage_source)

/**
 * Generates injuries from the resulting condition of the bodypart.
 *
 * The current bodypart state determines severity, while the latest hit
 * determines how that state was produced.
 *
 * This allows injuries to accumulate over multiple hits instead of being
 * determined exclusively by the size of a single damage instance.
 */
/obj/item/bodypart/proc/try_generate_injuries(brute = 0, burn = 0, sharpness = NONE, attack_direction = null, damage_source, wound_bonus = 0, exposed_wound_bonus = 0)
	if(wound_bonus == CANT_WOUND)
		return

	if(!is_woundable())
		return

	var/physical_ratio = get_physical_damage_ratio()
	var/skin_ratio = get_skin_damage_ratio()
	var/physical_integrity = 1 - physical_ratio
	// var/skin_integrity = 1 - skin_ratio

	var/structural_hit = brute > 0
	var/thermal_hit = burn > 0

	// Kinetic energy factor: larger single hits relative to limb health are far more likely
	// to produce severe injuries even if accumulated damage is still moderate.
	var/hit_energy = 0
	if(max_damage > 0)
		hit_energy = clamp((brute + burn) / max_damage, 0, 2.5)
	var/energy_bonus = hit_energy * 35 // added to chance rolls

	/*
	 * ------------------------------------------------------------
	 * SKIN / SUPERFICIAL TISSUE
	 * ------------------------------------------------------------
	 */

	if(thermal_hit)
		if(skin_ratio >= 0.80)
			apply_generated_injury(/datum/injury/burn/critical, attack_direction, damage_source)
		else if(skin_ratio >= 0.45)
			apply_generated_injury(/datum/injury/burn/severe, attack_direction, damage_source)
		else if(skin_ratio >= 0.12)
			apply_generated_injury(/datum/injury/burn, attack_direction, damage_source)

		if(skin_ratio >= 0.35)
			apply_generated_injury(/datum/injury/skin_damage, attack_direction, damage_source, clamp((skin_ratio - 0.25) * 160, 20, 100))

	/*
	 * ------------------------------------------------------------
	 * SHARP TRAUMA
	 * ------------------------------------------------------------
	 */

	if(structural_hit && (sharpness & SHARP_EDGED))
		if(physical_ratio >= 0.70)
			apply_generated_injury(/datum/injury/laceration/critical, attack_direction, damage_source)
		else if(physical_ratio >= 0.35)
			apply_generated_injury(/datum/injury/laceration/severe, attack_direction, damage_source)
		else if(physical_ratio >= 0.08)
			apply_generated_injury(/datum/injury/laceration, attack_direction, damage_source)

	if(structural_hit && (sharpness & SHARP_POINTY))
		if(physical_ratio >= 0.65 && brute >= max_damage * 0.20)
			apply_generated_injury(/datum/injury/avulsion, attack_direction, damage_source)
		else
			apply_generated_injury(/datum/injury/puncture, attack_direction, damage_source, clamp(40 + physical_ratio * 100 + energy_bonus, 40, 100))

	/*
	 * ------------------------------------------------------------
	 * BLUNT STRUCTURAL DAMAGE
	 * ------------------------------------------------------------
	 */

	if(structural_hit && !(sharpness & (SHARP_EDGED | SHARP_POINTY)))
		if(physical_ratio >= 0.08)
			if(physical_ratio >= 0.40)
				apply_generated_injury(/datum/injury/contusion/severe, attack_direction, damage_source)
			else
				apply_generated_injury(/datum/injury/contusion, attack_direction, damage_source)

		if(physical_ratio >= 0.30)
			apply_generated_injury(/datum/injury/fracture, attack_direction, damage_source, clamp(45 + (physical_ratio - 0.30) * 120 + energy_bonus, 45, 100))

		if(physical_ratio >= 0.65)
			apply_generated_injury(/datum/injury/fracture/compound, attack_direction, damage_source, clamp((physical_ratio - 0.55) * 220 + energy_bonus * 0.8, 30, 100))

	/*
	 * ------------------------------------------------------------
	 * SOFT-TISSUE DESTRUCTION
	 * ------------------------------------------------------------
	 */

	if(structural_hit && physical_ratio >= 0.50)
		apply_generated_injury(/datum/injury/nerve_damage, attack_direction, damage_source, clamp(35 + physical_ratio * 80, 35, 100))

	/*
	 * ------------------------------------------------------------
	 * LIMB-SPECIFIC JOINT FAILURE
	 * ------------------------------------------------------------
	 */

	if(structural_hit && (body_zone in list(BODY_ZONE_L_ARM, BODY_ZONE_R_ARM, BODY_ZONE_L_LEG, BODY_ZONE_R_LEG)) && physical_ratio >= 0.55)
		apply_generated_injury(/datum/injury/dislocation, attack_direction, damage_source, clamp((physical_ratio - 0.45) * 150, 20, 85))

	/*
	 * ------------------------------------------------------------
	 * HEAD TRAUMA
	 * ------------------------------------------------------------
	 */

	if(structural_hit && body_zone == BODY_ZONE_HEAD)
		if(physical_ratio >= 0.12)
			apply_generated_injury(/datum/injury/concussion, attack_direction, damage_source, clamp(45 + physical_ratio * 70 + energy_bonus, 45, 100))

		if(physical_ratio >= 0.32)
			apply_generated_injury(/datum/injury/skull_fracture, attack_direction, damage_source, clamp((physical_ratio - 0.25) * 180 + energy_bonus, 30, 100))

		if(physical_ratio >= 0.55)
			apply_generated_injury(/datum/injury/facial_trauma, attack_direction, damage_source, clamp((physical_ratio - 0.45) * 180 + energy_bonus * 0.7, 25, 100))

		if(physical_ratio >= 0.35 && ((sharpness & (SHARP_EDGED | SHARP_POINTY)) || physical_ratio >= 0.65))
			apply_generated_injury(/datum/injury/eye_trauma, attack_direction, damage_source, clamp((physical_ratio - 0.30) * 160 + energy_bonus, 20, 80))

		if(physical_ratio >= 0.60)
			apply_generated_injury(/datum/injury/jaw_fracture, attack_direction, damage_source, clamp((physical_ratio - 0.50) * 140 + energy_bonus * 0.6, 20, 70))

	/*
	 * ------------------------------------------------------------
	 * CHEST TRAUMA
	 * ------------------------------------------------------------
	 *
	 * The chest is treated as a collection of structures that can fail
	 * independently: ribs, lungs, pleura, vessels and the heart.
	 */

	if(structural_hit && body_zone == BODY_ZONE_CHEST)
		var/chest_severity = physical_ratio

		if(chest_severity >= 0.22)
			apply_generated_injury(/datum/injury/rib_fracture, attack_direction, damage_source, clamp(40 + chest_severity * 70 + energy_bonus, 40, 100))

		if(chest_severity >= 0.58)
			apply_generated_injury(/datum/injury/rib_fracture/flail, attack_direction, damage_source, clamp((chest_severity - 0.50) * 180 + energy_bonus * 0.7, 25, 90))

		if(chest_severity >= 0.40)
			apply_generated_injury(/datum/injury/internal_bleeding, attack_direction, damage_source, clamp((chest_severity - 0.30) * 130 + energy_bonus, 20, 85))

		if(chest_severity >= 0.32 && (sharpness & SHARP_POINTY))
			apply_generated_injury(/datum/injury/pneumothorax, attack_direction, damage_source, clamp(60 + chest_severity * 50 + energy_bonus, 60, 100))
		else if(chest_severity >= 0.60)
			apply_generated_injury(/datum/injury/pneumothorax, attack_direction, damage_source, clamp((chest_severity - 0.50) * 140 + energy_bonus * 0.6, 15, 70))

		if(chest_severity >= 0.52)
			apply_generated_injury(/datum/injury/hemothorax, attack_direction, damage_source, clamp((chest_severity - 0.45) * 150, 15, 70))

		if(chest_severity >= 0.68)
			apply_generated_injury(/datum/injury/cardiac_trauma, attack_direction, damage_source, clamp((chest_severity - 0.60) * 180, 15, 75))

		if(chest_severity >= 0.72)
			apply_generated_injury(/datum/injury/spleen_rupture, attack_direction, damage_source, clamp((chest_severity - 0.65) * 140, 10, 55))

	/*
	 * ------------------------------------------------------------
	 * VASCULAR DAMAGE
	 * ------------------------------------------------------------
	 */

	if(structural_hit)
		var/vascular_chance = 0

		if(sharpness & SHARP_EDGED)
			vascular_chance = 30 + physical_ratio * 70
		else if(sharpness & SHARP_POINTY)
			vascular_chance = 35 + physical_ratio * 65
		else if(physical_ratio >= 0.45)
			vascular_chance = (physical_ratio - 0.35) * 100

		if(vascular_chance > 0)
			if(physical_ratio >= 0.60 && (sharpness & (SHARP_EDGED | SHARP_POINTY)) && prob(vascular_chance * 0.45))
				apply_generated_injury(/datum/injury/arterial_bleed, attack_direction, damage_source)
			else if(prob(vascular_chance))
				apply_generated_injury(/datum/injury/venous_bleed, attack_direction, damage_source)

	/*
	 * ------------------------------------------------------------
	 * AVULSION / CATASTROPHIC TISSUE FAILURE
	 * ------------------------------------------------------------
	 */

	if(structural_hit && physical_ratio >= 0.78 && ((sharpness & (SHARP_EDGED | SHARP_POINTY)) || brute >= max_damage * 0.25))
		apply_generated_injury(/datum/injury/avulsion, attack_direction, damage_source, clamp((physical_ratio - 0.70) * 250, 25, 100))

	if(structural_hit && physical_integrity <= 0.10)
		apply_generated_injury(/datum/injury/avulsion, attack_direction, damage_source, 100)
#endif
