#define GRASS_COLOR_FOREST       "#5B8C3E"
#define GRASS_COLOR_JUNGLE       "#3A9B4A"
#define GRASS_COLOR_SAVANNA      "#B8A84A"

#define GRASS_COLOR_FOREST_LIGHT "#6E9E4F"
#define GRASS_COLOR_FOREST_TALL  "#4A7A32"

#define GRASS_COLOR_JUNGLE_LIGHT "#4AAD5A"
#define GRASS_COLOR_JUNGLE_TALL  "#2E8B3A"

#define GRASS_COLOR_SAVANNA_LIGHT "#C9B85C"
#define GRASS_COLOR_SAVANNA_TALL  "#A0903A"



#define STONE_COLOR_GRANITE      "#695F61"
#define STONE_COLOR_MARBLE       "#848784"
#define STONE_COLOR_LIMESTONE    "#9E9987"
#define STONE_COLOR_SANDSTONE    "#7E685E"
#define STONE_COLOR_SLATE        "#464646"

#define STONE_COLOR_BASALT       "#3A3A3C"
#define STONE_COLOR_QUARTZITE    "#A8A6A0"


#define SAND_COLOR_NORMAL        "#C2B280"
#define SAND_COLOR_CHALK         "#E8E0D0"
#define SAND_COLOR_RED           "#C47A5A"
#define SAND_COLOR_BLACK         "#4A4540"
#define SAND_COLOR_WHITE         "#F0EDE4"
#define SAND_COLOR_YELLOW        "#D4B86A"
#define SAND_COLOR_ORANGE        "#D4925A"
#define SAND_COLOR_PINK          "#D4A8A0"
#define SAND_COLOR_SILVER        "#B8C0C8"
#define SAND_COLOR_GOLDEN        "#D4B060"
#define SAND_COLOR_DARK          "#8A7A60"
#define SAND_COLOR_ASH           "#A0A090"
