// === Disarm ===
#define RW_DISARM_BASE_CHANCE 40
#define RW_DISARM_PER_SKILL 7.0
#define RW_DISARM_KNOCKDOWN_CHANCE_BASE 18
#define RW_DISARM_KNOCKDOWN_SKILL_THRESHOLD 8

// === Grab ===
#define RW_GRAB_SKILL_DIFF_MULT 8.5
