#define RIMWORLD_STUFF_METALLIC		"Metallic"
#define RIMWORLD_STUFF_STONY		"Stony"
#define RIMWORLD_STUFF_WOODY		"Woody"
#define RIMWORLD_STUFF_LEATHERY		"Leathery"
#define RIMWORLD_STUFF_FABRIC		"Fabric"
#define RIMWORLD_STUFF_BIOFERRITE	"Bioferrite"


#define RIMWORLD_STAT_BEAUTY_FACTOR		"beauty_factor"
#define RIMWORLD_STAT_BEAUTY_OFFSET		"beauty_offset"
#define RIMWORLD_STAT_HP_FACTOR			"hp_factor"
#define RIMWORLD_STAT_FLAMMABILITY		"flammability_factor"
#define RIMWORLD_STAT_ARMOR_SHARP		"armor_sharp"
#define RIMWORLD_STAT_ARMOR_BLUNT		"armor_blunt"
#define RIMWORLD_STAT_ARMOR_HEAT		"armor_heat"
#define RIMWORLD_STAT_MELEE_SHARP		"melee_sharp"
#define RIMWORLD_STAT_MELEE_BLUNT		"melee_blunt"
#define RIMWORLD_STAT_MELEE_COOLDOWN	"melee_cooldown"
#define RIMWORLD_STAT_INSULATION_COLD	"insulation_cold"
#define RIMWORLD_STAT_INSULATION_HEAT	"insulation_heat"
#define RIMWORLD_STAT_WORK_TO_MAKE		"work_to_make"
#define RIMWORLD_STAT_WORK_TO_BUILD		"work_to_build"
#define RIMWORLD_STAT_DOOR_SPEED		"door_opening_speed"
#define RIMWORLD_STAT_REST_EFFECT		"rest_effectiveness"
#define RIMWORLD_STAT_MARKET_VALUE		"market_value"


#define GET_RIMWORLD_STAT(mat, stat)			(istype(mat, /datum/material/rimworld_material) ? mat.rimworld_stats[stat] : null)
#define GET_RIMWORLD_BEAUTY_FACTOR(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_BEAUTY_FACTOR)
#define GET_RIMWORLD_BEAUTY_OFFSET(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_BEAUTY_OFFSET)
#define GET_RIMWORLD_HP_FACTOR(mat)				GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_HP_FACTOR)
#define GET_RIMWORLD_FLAMMABILITY(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_FLAMMABILITY)
#define GET_RIMWORLD_ARMOR_SHARP(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_ARMOR_SHARP)
#define GET_RIMWORLD_ARMOR_BLUNT(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_ARMOR_BLUNT)
#define GET_RIMWORLD_ARMOR_HEAT(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_ARMOR_HEAT)
#define GET_RIMWORLD_MELEE_SHARP(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_MELEE_SHARP)
#define GET_RIMWORLD_MELEE_BLUNT(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_MELEE_BLUNT)
#define GET_RIMWORLD_MELEE_COOLDOWN(mat)		GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_MELEE_COOLDOWN)
#define GET_RIMWORLD_INSULATION_COLD(mat)		GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_INSULATION_COLD)
#define GET_RIMWORLD_INSULATION_HEAT(mat)		GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_INSULATION_HEAT)
#define GET_RIMWORLD_MARKET_VALUE(mat)			GET_RIMWORLD_STAT(mat, RIMWORLD_STAT_MARKET_VALUE)

#define RIMWORLD_DEFAULT_BEAUTY_FACTOR		1
#define RIMWORLD_DEFAULT_BEAUTY_OFFSET		0
#define RIMWORLD_DEFAULT_HP_FACTOR			1
#define RIMWORLD_DEFAULT_FLAMMABILITY		1
#define RIMWORLD_DEFAULT_ARMOR_SHARP		1
#define RIMWORLD_DEFAULT_ARMOR_BLUNT		1
#define RIMWORLD_DEFAULT_ARMOR_HEAT			1
#define RIMWORLD_DEFAULT_MELEE_SHARP		1
#define RIMWORLD_DEFAULT_MELEE_BLUNT		1
#define RIMWORLD_DEFAULT_MELEE_COOLDOWN		1
#define RIMWORLD_DEFAULT_INSULATION_COLD	0
#define RIMWORLD_DEFAULT_INSULATION_HEAT	0
#define RIMWORLD_DEFAULT_WORK_TO_MAKE		1
#define RIMWORLD_DEFAULT_WORK_TO_BUILD		1
#define RIMWORLD_DEFAULT_DOOR_SPEED			1
#define RIMWORLD_DEFAULT_REST_EFFECT		1
