#define RW_RESEARCH_STARTING		(1<<0)
#define RW_RESEARCH_HIDDEN			(1<<1)
#define RW_RESEARCH_DISABLED		(1<<2)


#define RW_TECH_ERA_NEOLITHIC		"neolithic"
#define RW_TECH_ERA_MEDIEVAL		"medieval"
#define RW_TECH_ERA_INDUSTRIAL		"industrial"
#define RW_TECH_ERA_SPACER			"spacer"
#define RW_TECH_ERA_ULTRATECH		"ultratech"

#define RW_TECH_ERAS list(\
	RW_TECH_ERA_NEOLITHIC,\
	RW_TECH_ERA_MEDIEVAL,\
	RW_TECH_ERA_INDUSTRIAL,\
	RW_TECH_ERA_SPACER,\
	RW_TECH_ERA_ULTRATECH\
)

#define RW_TECH_ERA_ORDER list(\
	RW_TECH_ERA_NEOLITHIC,\
	RW_TECH_ERA_MEDIEVAL,\
	RW_TECH_ERA_INDUSTRIAL,\
	RW_TECH_ERA_SPACER,\
	RW_TECH_ERA_ULTRATECH\
)


#define RW_RESEARCH_BASE_PROGRESS		1
#define RW_RESEARCH_CYCLE_TIME			12 SECONDS
#define RW_RESEARCH_IDEAL_SKILL			8



#define RW_ARCHITECT_TAB_STRUCTURE		"Structure"
#define RW_ARCHITECT_TAB_FURNITURE		"Furniture"
#define RW_ARCHITECT_TAB_PRODUCTION		"Production"
#define RW_ARCHITECT_TAB_POWER			"Power"
#define RW_ARCHITECT_TAB_SECURITY		"Security"
#define RW_ARCHITECT_TAB_MISC			"Misc"

#define RW_ARCHITECT_TABS list(\
	RW_ARCHITECT_TAB_STRUCTURE,\
	RW_ARCHITECT_TAB_FURNITURE,\
	RW_ARCHITECT_TAB_PRODUCTION,\
	RW_ARCHITECT_TAB_POWER,\
	RW_ARCHITECT_TAB_SECURITY,\
	RW_ARCHITECT_TAB_MISC\
)
