/**
 * /datum/injury
 *
 * Medical conditions applied to a /obj/item/bodypart.
 * Most combat consequences live here (bleed, pain, disable, damage mult),
 *
 * Injuries of the same series upgrade or absorb instead of stacking.
 * Treatment reduces bleeding / pain and accelerates healing.
 * Fully healed injuries remove themselves.
 */

/datum/injury
	var/name = "Injury"
	var/undiagnosed_name
	var/desc = ""
	var/examine_desc = "is injured"

	/// INJURY_VISIBILITY_*
	var/visibility = INJURY_VISIBILITY_SELF

	/// INJURY_SEVERITY_*
	var/severity = INJURY_SEVERITY_MODERATE

	/// Series id — same series upgrades instead of stacking (e.g. "laceration", "burn")
	var/series = "generic"

	/// Typepath to upgrade into when this injury is intensified. Null = max tier.
	var/upgrade_path

	var/mob/living/carbon/owner
	var/obj/item/bodypart/limb

	/// Processed from carbon Life when TRUE
	var/processes = FALSE

	var/bleed_rate = 0
	var/pain_amount = 0
	/// Immediate shock generated when this injury is applied/intensified. 0 = derive from severity/pain/bleeding.
	var/initial_shock = 0
	/// Immediate consciousness impact generated by this injury. 0 = derive automatically.
	var/initial_consciousness_impact = 0
	var/damage_multiplier = 1.0

	/// Contribution of this injury toward catastrophic structural failure and dismemberment.
	var/dismemberment_weight = 0

	var/interaction_penalty = 1.0
	var/limp_slowdown = 0
	var/limp_chance = 0

	var/disabling = FALSE

	/// Associative list of item typepaths to treatment effectiveness.
	/// Missing effectiveness defaults to INJURY_TREATMENT_EFFECTIVENESS_NORMAL.
	var/list/treatable_by
	var/list/treatable_tools
	var/base_treat_time = 5 SECONDS

	var/injury_flags = NONE
	var/injury_source = "Unknown"
	var/unique_id

	/// INJURY_TREATMENT_NONE / POOR / ADEQUATE / EXCELLENT
	var/treatment_quality = INJURY_TREATMENT_NONE

	/// Healing progress from 0.0 to 1.0. Reaches 1.0 → injury is removed.
	var/healing_progress = 0

	/// Base healing rate per second toward 1.0.
	/// 0 means the injury will not progress without treatment (unless SELF_HEALING).
	var/base_healing_rate = 0

	/// Multiplier applied to bleed_rate after successful treatment.
	var/treated_bleed_mult = 1.0

	/// Multiplier applied to base_healing_rate after successful treatment.
	var/treated_heal_mult = 1.0

	/// Multiplier applied to pain_amount after successful treatment.
	var/treated_pain_mult = 1.0

	/// Continuous treatment effectiveness provided by skill-based medicine.
	/// 0 means the injury has not received skill-based medical treatment.
	var/treatment_effectiveness = 0

	/// Set by promote() for intermediate tiers so a multi-tier upgrade applies the shock response only once.
	var/skip_initial_response = FALSE


/datum/injury/New()
	unique_id = REF(src)
	return ..()

/datum/injury/Destroy()
	unregister_effects()
	if(limb)
		remove_from_limb()
	return ..()


/**
 * Applies this injury to a limb, or upgrades an existing injury of the same series.
 * Returns the final injury datum (may be an existing one that was upgraded), or null.
 */
/datum/injury/proc/apply_to_limb(obj/item/bodypart/target_limb, silent = FALSE, attack_direction = null, source = "Unknown")
	if(!target_limb || !can_apply_to(target_limb))
		qdel(src)
		return null

	// Same series already present — upgrade or absorb instead of stacking
	var/datum/injury/existing = target_limb.find_injury_series(series)
	if(existing)
		return existing.try_upgrade_from(src, silent, attack_direction, source)

	limb = target_limb
	owner = target_limb.owner

	if(isatom(source))
		var/atom/atom_source = source
		injury_source = atom_source.name
	else if(istext(source))
		injury_source = source

	LAZYADD(limb.injuries, src)
	if(owner)
		LAZYADD(owner.all_injuries, src)

	RegisterSignal(limb, COMSIG_QDELETING, PROC_REF(on_limb_qdel))

	on_apply(silent, attack_direction)
	limb.update_injuries()
	return src

/datum/injury/proc/can_apply_to(obj/item/bodypart/target_limb)
	return TRUE

/**
 * Called when another injury of the same series tries to apply.
 * src is the existing injury; incoming is the new one (will be qdeleted).
 * Returns the injury that remains on the limb.
 */
/datum/injury/proc/try_upgrade_from(datum/injury/incoming, silent = FALSE, attack_direction = null, source = "Unknown")
	// Incoming is weaker or equal — slight intensify, no new injury
	if(incoming.severity <= severity)
		absorb_intensity(incoming)
		qdel(incoming)
		limb?.update_injuries()
		return src

	// Incoming is stronger — upgrade along path or replace with incoming type
	var/datum/injury/result = src
	if(upgrade_path && incoming.severity > severity)
		result = promote(silent, attack_direction, source, FALSE)
		// If still below incoming severity and can promote further, keep going
		while(result && result.upgrade_path && result.severity < incoming.severity)
			var/datum/injury/next = result.promote(TRUE, attack_direction, source, FALSE)
			if(!next || next == result)
				break
			result = next
		// Shock/consciousness response for the whole upgrade chain is applied once, for the final tier.
		if(result && result.owner)
			result.owner.apply_injury_response(result)
	else if(incoming.type != type && incoming.severity > severity)
		// Different subtype, higher severity — replace entirely
		result = replace_with(incoming, silent, attack_direction, source)
		return result

	qdel(incoming)
	return result

/**
 * Mild intensify when hit again with same/lower severity (bleed/pain bump).
 * Also slightly resets healing progress so repeated trauma delays recovery.
 */
/datum/injury/proc/absorb_intensity(datum/injury/incoming)
	if(incoming.bleed_rate > 0)
		bleed_rate = min(bleed_rate + incoming.bleed_rate * 0.25, bleed_rate * 1.5 + 0.5)
	if(incoming.pain_amount > 0)
		pain_amount = min(pain_amount + incoming.pain_amount * 0.2, pain_amount * 1.35 + 5)

	// Re-injury slows healing
	if(healing_progress > 0)
		healing_progress = max(healing_progress - 0.15, 0)

	if(treatment_effectiveness > 0)
		treatment_effectiveness = max(treatment_effectiveness - 0.10, 0)

	if(limb?.owner)
		limb.owner.apply_injury_response(incoming)

/**
 * Promote this injury one step along upgrade_path. Returns the new injury.
 */
/datum/injury/proc/promote(silent = FALSE, attack_direction = null, source = "Unknown", apply_response = TRUE)
	if(!upgrade_path || !limb)
		return src

	var/obj/item/bodypart/cached_limb = limb
	var/mob/living/carbon/cached_owner = owner
	var/old_source = injury_source
	var/old_treatment = treatment_quality
	var/old_treatment_effectiveness = treatment_effectiveness
	var/old_healing = healing_progress

	// Detach without scarring logic
	remove_from_limb(replaced = TRUE)

	var/datum/injury/upgraded = new upgrade_path()
	upgraded.injury_source = istext(source) ? source : old_source
	// Carry over partial treatment/healing so promotion does not fully reset care
	upgraded.treatment_quality = old_treatment
	upgraded.treatment_effectiveness = old_treatment_effectiveness * 0.5
	upgraded.healing_progress = old_healing * 0.5
	upgraded.on_treated(old_treatment, null) // re-apply multipliers for the new tier
	upgraded.skip_initial_response = !apply_response

	// Force apply without series check recursion — series matches, limb empty of us
	upgraded.limb = cached_limb
	upgraded.owner = cached_owner
	LAZYADD(cached_limb.injuries, upgraded)
	if(cached_owner)
		LAZYADD(cached_owner.all_injuries, upgraded)
	RegisterSignal(cached_limb, COMSIG_QDELETING, TYPE_PROC_REF(/datum/injury, on_limb_qdel))
	upgraded.on_apply(silent, attack_direction)
	cached_limb.update_injuries()
	qdel(src)
	return upgraded

/**
 * Replace this injury with incoming (already instantiated). Incoming must not be on a limb yet.
 */
/datum/injury/proc/replace_with(datum/injury/incoming, silent = FALSE, attack_direction = null, source = "Unknown")
	var/obj/item/bodypart/cached_limb = limb
	remove_from_limb(replaced = TRUE)
	// incoming.apply_to_limb would series-check again; apply directly
	incoming.limb = cached_limb
	incoming.owner = cached_limb?.owner
	if(isatom(source))
		var/atom/atom_source = source
		incoming.injury_source = atom_source.name
	else if(istext(source))
		incoming.injury_source = source
	LAZYADD(cached_limb.injuries, incoming)
	if(incoming.owner)
		LAZYADD(incoming.owner.all_injuries, incoming)
	RegisterSignal(cached_limb, COMSIG_QDELETING, TYPE_PROC_REF(/datum/injury, on_limb_qdel))
	incoming.on_apply(silent, attack_direction)
	cached_limb.update_injuries()
	qdel(src)
	return incoming

/datum/injury/proc/on_apply(silent = FALSE, attack_direction = null)
	if(disabling && limb)
		limb.add_traits(list(TRAIT_PARALYSIS, TRAIT_DISABLED_BY_INJURY), unique_id)
	if(owner && !skip_initial_response)
		owner.apply_injury_response(src)
	skip_initial_response = FALSE
	if(!silent)
		show_application_message()

	// Self-healing injuries start processing immediately
	if((injury_flags & INJURY_FLAG_SELF_HEALING) && base_healing_rate > 0)
		processes = TRUE

	// Internal bleeders drain blood in process_internal_bleeding(), so they must always process
	if(is_internal_bleeder())
		processes = TRUE

	register_effects()
	if(!silent)
		on_applied_effects(attack_direction)

/datum/injury/proc/get_initial_shock()
	if(initial_shock > 0)
		return initial_shock

	var/value = INJURY_SHOCK_BASE
	value += severity * INJURY_SHOCK_PER_SEVERITY
	value += pain_amount * INJURY_SHOCK_PAIN_FACTOR
	value += max(get_bleed_rate(), 0) * INJURY_SHOCK_BLEED_FACTOR

	if(limb?.body_zone == BODY_ZONE_HEAD)
		value *= 1.25

	return value

/datum/injury/proc/get_initial_consciousness_impact()
	if(initial_consciousness_impact > 0)
		return initial_consciousness_impact

	var/value = INJURY_CONSCIOUSNESS_BASE
	value += severity * INJURY_CONSCIOUSNESS_PER_SEVERITY
	value += pain_amount * INJURY_CONSCIOUSNESS_PAIN_FACTOR

	if(limb?.body_zone == BODY_ZONE_HEAD)
		value *= INJURY_HEAD_CONSCIOUSNESS_MULT

	return value

/datum/injury/proc/remove_from_limb(replaced = FALSE)
	if(!limb)
		return

	UnregisterSignal(limb, COMSIG_QDELETING)
	unregister_effects(replaced)

	if(disabling)
		limb.remove_traits(list(TRAIT_PARALYSIS, TRAIT_DISABLED_BY_INJURY), unique_id)

	LAZYREMOVE(limb.injuries, src)
	if(owner)
		LAZYREMOVE(owner.all_injuries, src)

	on_remove(replaced)

	var/obj/item/bodypart/old_limb = limb
	limb = null
	owner = null

	old_limb.update_injuries()

/datum/injury/proc/on_remove(replaced = FALSE)
	return

/datum/injury/proc/on_limb_qdel(datum/source)
	SIGNAL_HANDLER
	limb = null
	owner = null
	qdel(src)


/datum/injury/proc/handle_process(seconds_per_tick)
	process_healing(seconds_per_tick)
	if(QDELETED(src) || !owner)
		return
	process_internal_bleeding(seconds_per_tick)
	if(owner.stat != DEAD)
		process_effects(seconds_per_tick)

/**
 * Advances healing progress. When progress reaches 1.0 the injury is removed.
 */
/datum/injury/proc/process_healing(seconds_per_tick)
	if(healing_progress >= 1)
		return

	var/rate = base_healing_rate

	if(treatment_effectiveness > 0)
		rate *= get_healing_treatment_multiplier()
	else if(treatment_quality == INJURY_TREATMENT_NONE)
		// Untreated: only self-healing injuries progress
		if(!(injury_flags & INJURY_FLAG_SELF_HEALING))
			return
	else
		rate *= treated_heal_mult

	if(rate <= 0)
		return

	healing_progress = min(healing_progress + rate * seconds_per_tick, 1)

	if(healing_progress >= 1)
		on_healed()

/**
 * Called when healing_progress reaches 1.0. Removes the injury.
 */
/datum/injury/proc/on_healed()
	if(owner)
		to_chat(owner, span_notice("Your [name] has fully healed."))
	remove_from_limb()
	qdel(src)



/datum/injury/proc/get_bleed_pressure_response()
	if(istype(src, /datum/injury/arterial_bleed))
		return 1.0
	if(istype(src, /datum/injury/venous_bleed))
		return 0.65
	if(injury_flags & INJURY_FLAG_INTERNAL)
		return 0.75
	return 0.60

/datum/injury/proc/get_bleed_pulse_response()
	if(istype(src, /datum/injury/arterial_bleed))
		return 0.20
	if(istype(src, /datum/injury/venous_bleed))
		return 0.05
	return 0.08

/**
 * Effective bleed rate after pressure, pulse and treatment modifiers.
 */
/datum/injury/proc/get_bleed_rate()
	if(bleed_rate <= 0)
		return 0
	if(!owner || HAS_TRAIT(owner, TRAIT_GODMODE))
		if(treatment_effectiveness > 0)
			return bleed_rate * get_bleed_treatment_multiplier()
		return bleed_rate * (treatment_quality > INJURY_TREATMENT_NONE ? treated_bleed_mult : 1)

	var/bp_ratio = clamp(owner.blood_pressure / BP_NORMAL, 0, 2)
	var/hr_ratio = clamp(owner.get_heart_rate() / HEART_RATE_NORMAL, 0, 2)

	var/pressure_response = get_bleed_pressure_response()
	var/pulse_response = get_bleed_pulse_response()

	// Flow is driven primarily by vascular pressure. Keep a small floor so
	// residual pressure/venous filling can still empty a wound after arrest.
	var/pressure_factor = 1 + ((bp_ratio - 1) * pressure_response)
	pressure_factor = clamp(pressure_factor, 0.10, 2.0)

	// Pulse has a deliberately small effect outside arterial bleeding.
	var/pulse_factor = 1 + ((hr_ratio - 1) * pulse_response)
	pulse_factor = clamp(pulse_factor, 0.70, 1.35)

	var/result = bleed_rate * pressure_factor * pulse_factor

	if(treatment_effectiveness > 0)
		result *= get_bleed_treatment_multiplier()
	else if(treatment_quality > INJURY_TREATMENT_NONE)
		result *= treated_bleed_mult

	return result

/**
 * Effective pain after treatment multiplier.
 */
/datum/injury/proc/get_pain()
	var/result = pain_amount
	if(treatment_effectiveness > 0)
		result *= get_pain_treatment_multiplier()
	else if(treatment_quality > INJURY_TREATMENT_NONE)
		result *= treated_pain_mult
	return result

/**
 * Returns the bleeding multiplier produced by continuous skill-based treatment.
 * Higher treatment effectiveness means less active bleeding.
 */
/datum/injury/proc/get_bleed_treatment_multiplier()
	return clamp(1 - (treatment_effectiveness * 0.75), 0.10, 1.0)

/**
 * Returns the healing multiplier produced by continuous skill-based treatment.
 * This deliberately scales continuously instead of using only treatment tiers.
 */
/datum/injury/proc/get_healing_treatment_multiplier()
	return 1 + (treatment_effectiveness * 2.0)

/**
 * Returns the pain multiplier produced by continuous skill-based treatment.
 */
/datum/injury/proc/get_pain_treatment_multiplier()
	return clamp(1 - (treatment_effectiveness * 0.50), 0.20, 1.0)

/**
 * Returns TRUE if skill-based medicine can still improve this injury.
 */
/datum/injury/proc/can_be_treated_by_medicine(effectiveness)
	if(effectiveness <= 0)
		return FALSE
	if(treatment_effectiveness >= effectiveness)
		return FALSE
	return TRUE

/**
 * Applies continuous treatment directly to this injury.
 *
 * Unlike the legacy item treatment path, this does not collapse the result
 * into a discrete quality tier. The medicine effectiveness and the user's
 * Medical skill determine the actual treatment strength.
 */
/datum/injury/proc/treat_with_medicine(mob/living/user, effectiveness)
	if(!can_be_treated_by_medicine(effectiveness))
		return FALSE

	treatment_effectiveness = max(treatment_effectiveness, effectiveness)

	// Keep the existing treatment-quality field useful for old UI and systems.
	var/new_quality = INJURY_TREATMENT_POOR
	if(effectiveness >= INJURY_TREATMENT_EFFECTIVENESS_EXCELLENT)
		new_quality = INJURY_TREATMENT_EXCELLENT
	else if(effectiveness >= INJURY_TREATMENT_EFFECTIVENESS_ADEQUATE)
		new_quality = INJURY_TREATMENT_ADEQUATE

	if(new_quality > treatment_quality)
		treatment_quality = new_quality

	// Use the normal treatment hook so healing processing is enabled.
	on_treated(treatment_quality, user)
	processes = TRUE

	if(owner && !HAS_TRAIT(owner, TRAIT_GODMODE) && user)
		to_chat(owner, span_notice("The treatment improves the condition of your [name]."))

	limb?.update_injuries()
	return TRUE

/datum/injury/proc/get_damage_multiplier()
	return damage_multiplier


/datum/injury/proc/try_treat(obj/item/tool, mob/living/user)
	if(!item_can_treat(tool, user))
		return FALSE
	return treat(tool, user)

/datum/injury/proc/get_item_treatment_effectiveness(obj/item/tool)
	if(!tool)
		return 0

	if(length(treatable_tools) && (tool.tool_behaviour in treatable_tools))
		return INJURY_TREATMENT_EFFECTIVENESS_NORMAL

	if(!length(treatable_by))
		return 0

	for(var/typepath in treatable_by)
		if(!istype(tool, typepath))
			continue

		var/effectiveness = treatable_by[typepath]
		if(isnull(effectiveness))
			return INJURY_TREATMENT_EFFECTIVENESS_NORMAL

		return max(0, effectiveness)

	return 0

/datum/injury/proc/item_can_treat(obj/item/tool, mob/user)
	if(treatment_quality >= INJURY_TREATMENT_EXCELLENT)
		return FALSE
	return get_item_treatment_effectiveness(tool) > 0

/**
 * Default treatment implementation.
 * Subtypes may override for special behaviour (surgery steps, etc.).
 */
/datum/injury/proc/treat(obj/item/tool, mob/user)
	if(!can_be_treated_by(tool, user))
		return FALSE

	var/quality = resolve_treatment_quality(tool, user)

	if(!do_after(user, base_treat_time, target = owner || user))
		return FALSE

	if(apply_treatment(quality, user))
		if(isstack(tool))
			var/obj/item/stack/stack_tool = tool
			stack_tool.use(1)
		return TRUE
	return FALSE

/datum/injury/proc/can_be_treated_by(obj/item/tool, mob/user)
	return item_can_treat(tool, user)

/**
 * Determines treatment quality from tool and (optionally) user skill.
 * Override or extend later for skill-based quality.
 */
/datum/injury/proc/resolve_treatment_quality(obj/item/tool, mob/user)
	var/effectiveness = get_item_treatment_effectiveness(tool)
	if(effectiveness >= INJURY_TREATMENT_EFFECTIVENESS_EXCELLENT)
		return INJURY_TREATMENT_EXCELLENT
	if(effectiveness >= INJURY_TREATMENT_EFFECTIVENESS_ADEQUATE)
		return INJURY_TREATMENT_ADEQUATE
	if(effectiveness >= INJURY_TREATMENT_EFFECTIVENESS_POOR)
		return INJURY_TREATMENT_POOR
	return INJURY_TREATMENT_NONE

/**
 * Applies treatment of the given quality. Improves multipliers and enables healing.
 * Returns TRUE if quality was actually improved.
 */
/datum/injury/proc/apply_treatment(quality = INJURY_TREATMENT_ADEQUATE, mob/user)
	if(quality <= treatment_quality)
		return FALSE

	treatment_quality = quality
	on_treated(quality, user)
	limb?.update_injuries()
	return TRUE

/**
 * Sets bleed/heal/pain multipliers according to treatment quality
 * and ensures the injury is processed for healing.
 */
/datum/injury/proc/on_treated(quality, mob/user)
	switch(quality)
		if(INJURY_TREATMENT_POOR)
			treated_bleed_mult = 0.55
			treated_heal_mult  = 1.4
			treated_pain_mult  = 0.85
		if(INJURY_TREATMENT_ADEQUATE)
			treated_bleed_mult = 0.25
			treated_heal_mult  = 2.2
			treated_pain_mult  = 0.65
		if(INJURY_TREATMENT_EXCELLENT)
			treated_bleed_mult = 0.08
			treated_heal_mult  = 3.5
			treated_pain_mult  = 0.45
		else
			treated_bleed_mult = 1.0
			treated_heal_mult  = 1.0
			treated_pain_mult  = 1.0

	// Treatment enables healing processing
	if(base_healing_rate > 0 || (injury_flags & INJURY_FLAG_SELF_HEALING))
		processes = TRUE

	if(owner && !HAS_TRAIT(owner, TRAIT_GODMODE) && user)
		to_chat(owner, span_notice("The treatment eases the pain of your [name]."))


/datum/injury/proc/get_ui_data()
	return list(
		"id" = unique_id,
		"name" = name,
		"undiagnosed_name" = undiagnosed_name || name,
		"severity" = severity,
		"severity_text" = severity_text(),
		"desc" = desc,
		"examine_desc" = examine_desc,
		"bleed_rate" = get_bleed_rate(),
		"pain" = get_pain(),
		"disabling" = disabling,
		"can_treat" = !!(treatable_by || treatable_tools) && treatment_quality < INJURY_TREATMENT_EXCELLENT,
		"series" = series,
		"treatment_quality" = treatment_quality,
		"treatment_effectiveness" = treatment_effectiveness,
		"healing_progress" = healing_progress,
		"treated" = treatment_quality > INJURY_TREATMENT_NONE,
	)

/datum/injury/proc/severity_text()
	switch(severity)
		if(INJURY_SEVERITY_MINOR)
			return "Minor"
		if(INJURY_SEVERITY_MODERATE)
			return "Moderate"
		if(INJURY_SEVERITY_SEVERE)
			return "Severe"
		if(INJURY_SEVERITY_CRITICAL)
			return "Critical"
		if(INJURY_SEVERITY_LOSS)
			return "Loss"
	return "Unknown"

/datum/injury/proc/treatment_text()
	switch(treatment_quality)
		if(INJURY_TREATMENT_NONE)
			return "Untreated"
		if(INJURY_TREATMENT_POOR)
			return "Poorly treated"
		if(INJURY_TREATMENT_ADEQUATE)
			return "Treated"
		if(INJURY_TREATMENT_EXCELLENT)
			return "Expertly treated"
	return "Unknown"

/datum/injury/proc/get_examine_text(mob/user)
	if(!owner || !limb)
		return null
	return "[owner.p_Their()] [limb.plaintext_zone] [examine_desc]."

/datum/injury/proc/get_self_examine_text(self_aware = FALSE)
	var/shown_name = (self_aware || !undiagnosed_name) ? name : undiagnosed_name
	var/status = ""
	if(treatment_quality > INJURY_TREATMENT_NONE)
		status = " ([treatment_text()])"
	if(healing_progress > 0.05)
		status += " — healing ([round(healing_progress * 100)]%)"
	return "It's suffering from [shown_name][status]."

/datum/injury/proc/get_scanner_data(mob/user)
	return list(
		"name" = name,
		"severity" = severity_text(),
		"description" = desc,
		"treatment" = get_treatment_text(),
		"treatment_quality" = treatment_text(),
		"healing_progress" = round(healing_progress * 100),
		"bleed_rate" = get_bleed_rate(),
		"pain" = get_pain(),
	)

/datum/injury/proc/get_treatment_text()
	if(treatment_quality >= INJURY_TREATMENT_EXCELLENT)
		return "Already optimally treated."
	if(treatable_by || treatable_tools)
		return "Can be treated with appropriate medical supplies."
	return "See a doctor."

/datum/injury/proc/show_application_message()
	if(!owner || !limb)
		return
	owner.visible_message(
		span_danger("[owner]'s [limb.plaintext_zone] [occur_text()]!"),
		span_userdanger("Your [limb.plaintext_zone] [occur_text()]!"),
	)

/datum/injury/proc/can_be_seen_by(mob/viewer)
	if(!viewer)
		return FALSE
	switch(visibility)
		if(INJURY_VISIBILITY_NONE)
			return FALSE
		if(INJURY_VISIBILITY_SELF)
			return viewer == owner
		if(INJURY_VISIBILITY_MEDICAL)
			return viewer == owner || HAS_TRAIT(viewer, TRAIT_VIEW_FULL_HEALTH)
		if(INJURY_VISIBILITY_FULL)
			return TRUE
	return FALSE

/datum/injury/proc/occur_text()
	return "is injured"

