/datum/biome/rimworld
	var/biome_key

	/// Weighted list of possible open turf types.
	/// If empty, falls back to open_turf_type.
	var/list/open_turf_types = list()

	/// Weighted list of possible closed turf types.
	/// If empty, falls back to closed_turf_type.
	var/list/closed_turf_types = list()

	/// Optional secondary open turf used for geological transitions.
	var/open_turf_type_secondary

	/// Optional secondary closed turf used for geological transitions.
	var/closed_turf_type_secondary

	/// Chance of using the secondary turf on geological transitions.
	var/transition_chance = 35

	/**
	 * Optional height-based open turf table.
	 *
	 * The highest threshold <= height is selected.
	 *
	 * Example:
	 *
	 * list(
	 *     0.00 = /turf/open/floor/plating/dirt,
	 *     0.30 = /turf/open/floor/plating/grass,
	 *     0.60 = /turf/open/floor/plating/rocky,
	 *     0.82 = /turf/open/floor/plating/rock
	 * )
	 */
	var/list/open_turf_by_height = null

	/**
	 * Optional turf used for cells marked by the Rust cave mask.
	 *
	 * If null, the normal height-based open turf is used.
	 */
	var/open_turf_type_cave = null

/datum/biome/rimworld/New()
	. = ..()

	if(length(open_turf_types))
		open_turf_types = expand_weights(fill_with_ones(open_turf_types))

	if(length(closed_turf_types))
		closed_turf_types = expand_weights(fill_with_ones(closed_turf_types))


/**
 * Returns the open turf type for a normalized height value (0.0-1.0).
 *
 * The highest threshold that is <= height is selected.
 *
 * If no height table exists, the normal weighted open turf list is used.
 */
/datum/biome/rimworld/proc/get_open_turf_for_height(height)
	height = clamp(text2num("[height]"), 0, 1)

	if(open_turf_by_height && length(open_turf_by_height))
		var/best_threshold = null
		var/best_turf_type = null

		for(var/threshold in open_turf_by_height)
			var/t = text2num("[threshold]")
			if(isnull(t))
				continue

			if(height < t)
				continue

			if(isnull(best_threshold) || t > best_threshold)
				best_threshold = t
				best_turf_type = open_turf_by_height[threshold]

		if(best_turf_type)
			return best_turf_type

	if(length(open_turf_types))
		return pick(open_turf_types)

	return open_turf_type

/**
 * Picks an open turf while taking geological transitions into account.
 */
/datum/biome/rimworld/proc/pick_open_turf(turf/gen_turf, height = 0.5, is_transition = FALSE, is_cave = FALSE)
	if(is_cave && open_turf_type_cave)
		return open_turf_type_cave

	if(is_transition && open_turf_type_secondary && prob(transition_chance))
		return open_turf_type_secondary

	return get_open_turf_for_height(height)

/**
 * Picks a closed turf while taking geological transitions into account.
 */
/datum/biome/rimworld/proc/pick_closed_turf(turf/gen_turf, is_transition = FALSE)
	if(is_transition && closed_turf_type_secondary && prob(transition_chance))
		return closed_turf_type_secondary

	if(length(closed_turf_types))
		return pick(closed_turf_types)

	return closed_turf_type


/datum/biome/rimworld/populate_turfs(
	list/turf/target_turfs,
	flora_allowed,
	features_allowed,
	fauna_allowed
)
	var/has_flora = flora_allowed && length(flora_types)
	var/has_features = features_allowed && length(feature_types)
	var/has_fauna = fauna_allowed && length(fauna_types)

	if(!has_flora && !has_features && !has_fauna)
		return

	for(var/turf/target_turf as anything in target_turfs)
		// All turfs in this list were explicitly generated by the RimWorld
		// sub-level generator as open terrain.
		if(istype(target_turf, /turf/closed))
			continue

		CHECK_TICK

		if(target_turf.turf_flags & TURF_BLOCKS_POPULATE_TERRAIN_FLORAFEATURES)
			continue

		if(flora_allowed && prob(flora_density) && length(flora_types))
			var/flora_type = pick(flora_types)
			new flora_type(target_turf)
			continue

		if(features_allowed && prob(feature_density) && length(feature_types))
			var/picked_feature = pick(feature_types)
			new picked_feature(target_turf)
			continue

		if(fauna_allowed && prob(fauna_density) && length(fauna_types))
			var/picked_mob = pick(fauna_types)
			new picked_mob(target_turf)
